### ISSUE TITLE
Polish localization

### ISSUE THREAD

**Issue by pik-256** [PeculiarVentures/fortify-releases#16]
how can I contribute to polish localization? Is there any template file I could translate?
I have found and translated only "c:\Program Files\Fortify\locales\pl\tray.json" but it does not contain all app's messages:
```

{
  "about": "O Fortify",
  "updates": "Sprawdź aktualizacje...",
  "tools": "Narzędzia",
  "preferences": "Ustawienia...",
  "sign_with_hancock": "Podpisz używając Hancock",
  "quit": "Zakończ Fortify"
}

```

**Comment by Kharya1337** [comment]
Hi @pik-256 ,

Thank you for your interest in contributing to the localization of the app!

I’ve attached the English i18n files here. You can use these to translate the app into Polish. Once you’ve completed the translation, feel free to share the files, and we’ll be happy to integrate them in a future release.

Thanks again for your contribution, and let me know if you need any help along the way!

[action.json](https://github.com/user-attachments/files/17365967/action.json)
[translation.json](https://github.com/user-attachments/files/17366050/translation.json)

Best regards, 
Team Fortify

**Comment by pik-256** [comment]
I attach files translated
[action.json](https://github.com/user-attachments/files/17393775/action.json)
[translation.json](https://github.com/user-attachments/files/17393776/translation.json)
Finally, you need one more string in settings: "Polish":"polski"

**Comment by Kharya1337** [comment]
Hi @pik-256 ,

Thanks for providing the Polish translation! Apologies for the delay in getting back to you. I’ve reviewed the files, and everything looks good.

The Polish translation will be included in the next app release. I’ll keep you updated when it’s available.

Thanks again for your contribution!

Best regards,  
Team Fortify
